`define VALID 1
`define INVALID 0
`define DECISION_NODE 0
`define OUT_NODE 1
`define X_NUM 2
`define NODE  1
`define NS_T 8
`define NS_F  8
`define WIDTH 8
`define RAM_OUT 8
`define MAX 127
